### PR TITLE
update README

### LINKED ISSUE #17: Add preprocessing functions for README PyTorch tutorial code
# Motivation
Make the mnist tutorial code in the README easier to understand.

# Description
Write concrete examples of preprocessing functions.

# Additional context (optional)

### PR DESCRIPTION
**Pull request by cv-dote**
close #17 

# Motivation
Make the mnist tutorial code in the README easier to understand.

# Description of the changes
Write concrete examples of preprocessing functions.

# Example

### CODE REVIEW

**Comment by cv-dote** [comment]
The command reference section of the table of contents has changed, please let me know if you prefer the previous version. I don't think there's anything wrong with it though.

**Comment by sbilxxxx** [comment]
I checked the updated code of `preprocessing_func` .
I think `from torchvision import transforms` is missing.

**Comment by cv-dote** [comment]
You are right, I forgot the import statement. I will fix it.

**Review by kenichihiguchi — APPROVED** [review]
Nice

**Comment by kenichihiguchi** [comment]
@cv-dote 
thanks!
Could you insert an expranation for `preprocess_func` on commented area below?
```Python
from base import Project, Dataset

# export dataset as you want to use
project = Project("mnist")
files = project.files(conditions="train", query=["label in ['1','2','3']"])

print(files[0])
# this returns path-like `File` object
# -> '/home/xxxx/dataset/mnist/0/12909.png'
print(files[0].label)
# this returns the value of attribute 'lable' of first `File` object
# -> '0'

"""
here!
"""
dataset = Dataset(files, target_key="label", transform=preprocess_func)
x_train, x_test, y_train, y_test = dataset.train_test_split(split_rate=0.2)

# or use with torch
import torch
import torchvision.transforms as transforms
from PIL import Image

def preprocess_func(path):
        image = transforms.ToTensor()(transforms.Resize((28, 28))(Image.open(path)))
        return image

dataset = Dataset(files, target_key="label", transform=preprocess_func)
loader = torch.utils.data.DataLoader(dataset, batch_size=32, shuffle=True)
```

**Comment by cv-dote** [comment]
All right. I'll update it.

**Comment by cv-dote** [comment]
@kenichihiguchi 
Could you review new change?

**Comment by kenichihiguchi** [comment]
looks so good!
thank you!

**Pull request merged**
